[package]
name = "yggdrasil-vault"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"
tokio = { version = "1.36.0", features = ['full'] }
tonic = "0.11.0"
tonic-reflection = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
